use_frameworks!

platform :ios, '9.0'

target 'PrivateRepo_Example' do
  pod 'PrivateRepo', :path => '../'

  target 'PrivateRepo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
